# Generated by Django 4.2.7 on 2025-09-16 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_time", models.DateTimeField(auto_now=True)),
                ("total_score", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        default="default@example.com",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("mobile", models.CharField(default="0000000000", max_length=10)),
                ("stream", models.CharField(default="Not Specified", max_length=200)),
                (
                    "college_name",
                    models.CharField(default="Default College", max_length=300),
                ),
                ("skills", models.TextField(blank=True, default="")),
                ("ssc_grade", models.CharField(default="0.0", max_length=10)),
                ("intermediate_grade", models.CharField(default="0.0", max_length=10)),
                ("password", models.CharField(default="temp1234", max_length=12)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("group_discussion", "Group Discussion"),
                            ("technical", "Technical Round"),
                            ("hr_round", "HR Round"),
                        ],
                        default="assignment",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "group_discussion_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "technical_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "hr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("registration_time", models.DateTimeField(auto_now_add=True)),
                ("login_time", models.DateTimeField(blank=True, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.college",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("javascript", "JavaScript"),
                            ("python", "Python"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("csharp", "C#"),
                            ("php", "PHP"),
                            ("ruby", "Ruby"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.TextField()),
                ("test_passed", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.assignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCQAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("homepage", "General Knowledge"),
                            ("coding-theory", "Coding Theory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.CharField(max_length=10)),
                ("answer", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.assignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_exam_active", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "college",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.college",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.student"
            ),
        ),
    ]
