# Generated by Django 4.2.7 on 2025-09-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="aiml_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assignment",
            name="fullstack_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="logic_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assignment",
            name="programming_score",
            field=models.IntegerField(default=0),
        ),
    ]
