# Generated by Django 4.2.7 on 2025-09-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_evaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem",
                    models.CharField(
                        choices=[
                            ("leap", "Leap Year Checker"),
                            ("nextprime", "Next Prime Finder"),
                            ("hcf", "HCF of Two Numbers"),
                            ("median", "Median of Two Lists"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.TextField()),
                ("result", models.TextField()),
                ("score", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.student",
                    ),
                ),
            ],
        ),
    ]
