# Generated by Django 4.2.7 on 2025-09-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_evaluation_programming_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="aiml_score",
            field=models.IntegerField(
                default=0, help_text="AI/ML Score (out of 30 marks)"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="fullstack_score",
            field=models.IntegerField(
                default=0, help_text="Full Stack Score (out of 30 marks)"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="is_passed",
            field=models.BooleanField(
                default=False, help_text="Qualified for next round (≥160/200)"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="logic_score",
            field=models.IntegerField(
                default=0, help_text="Logic & Reasoning Score (out of 40 marks)"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="programming_score",
            field=models.IntegerField(
                default=0, help_text="Programming Score (out of 100 marks)"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="total_score",
            field=models.IntegerField(
                default=0, help_text="Total Score (out of 200 marks)"
            ),
        ),
        migrations.AlterField(
            model_name="mcqanswer",
            name="section",
            field=models.CharField(
                choices=[
                    ("homepage", "AI/ML Questions"),
                    ("coding-theory", "Full Stack Questions"),
                    ("logic-reasoning", "Logic & Reasoning Questions"),
                ],
                max_length=20,
            ),
        ),
    ]
