# Generated by Django 5.2.4 on 2025-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_technicalround_hrround_groupdiscussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester_cgpa',
            field=models.CharField(blank=True, default='0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
