# Generated by Django 5.2.4 on 2025-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_remove_student_skills_student_current_semester_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiscussion',
            name='gd_score',
            field=models.IntegerField(default=0, help_text='Group Discussion Score (manually entered by admin)'),
        ),
        migrations.AddField(
            model_name='technicalround',
            name='gd_score',
            field=models.IntegerField(default=0, help_text='Group Discussion Score from previous round'),
        ),
    ]
