# Generated by Django 5.2.4 on 2025-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_groupdiscussion_gd_score_technicalround_gd_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
