# Generated by Django 5.2.4 on 2025-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_student_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiscussion',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Total Score (Assignment + GD)'),
        ),
        migrations.AddField(
            model_name='hrround',
            name='gd_score',
            field=models.IntegerField(default=0, help_text='Group Discussion Score'),
        ),
        migrations.AddField(
            model_name='hrround',
            name='hr_score',
            field=models.IntegerField(default=0, help_text='HR Round Score (0-100, manually entered by admin)'),
        ),
        migrations.AddField(
            model_name='hrround',
            name='technical_score',
            field=models.IntegerField(default=0, help_text='Technical Round Score'),
        ),
        migrations.AddField(
            model_name='hrround',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Total Score (Assignment + GD + Technical + HR)'),
        ),
        migrations.AddField(
            model_name='technicalround',
            name='technical_score',
            field=models.IntegerField(default=0, help_text='Technical Round Score (0-100, manually entered by admin)'),
        ),
        migrations.AddField(
            model_name='technicalround',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Total Score (Assignment + GD + Technical)'),
        ),
        migrations.AlterField(
            model_name='groupdiscussion',
            name='gd_score',
            field=models.IntegerField(default=0, help_text='Group Discussion Score (0-100, manually entered by admin)'),
        ),
    ]
